name: 中青看点阅读二

on:
  workflow_dispatch:
  schedule:
     - cron: '0 1,3,7,10,14,18,22 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ2_1 }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2_2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3_3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4_4 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ5_5 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点阅读一】'
        if: env.YOUTH_READ
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2_1 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME }}

      - name: '运行 【中青看点阅读二】'
        if: env.YOUTH_READ2
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2_2 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME2 }}
          
      - name: '运行 【中青看点阅读三】'
        if: env.YOUTH_READ3
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3_3 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME3 }}
          
      - name: '运行 【中青看点阅读四】'
        if: env.YOUTH_READ4
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4_4 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME4 }}

      - name: '运行 【中青看点阅读五】'
        if: env.YOUTH_READ5
        run: |
          node Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ5_5 }}
          YOUTH_ATIME: ${{ secrets.YOUTH_ATIME5 }}
